name: ReadyAPI TestEngine Execution

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      project_name:
        description: 'ReadyAPI project to execute'
        required: true
        default: 'te-sample-readyapi-project.xml'
        type: string

env:
  TESTENGINE_URL: http://localhost:8080
  TESTENGINE_USERNAME: admin
  TESTENGINE_PASSWORD: admin
  SLM_ACCESS_KEY: ${{ secrets.TESTENGINE_LICENSE_KEY }}
  TE_SLM_SERVER: ${{ secrets.TE_SLM_SERVER }}

jobs:
  run-readyapi-tests:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Start TestEngine Container
      run: |
        echo "Starting TestEngine container..."
        
        # Check if SLM access key is available (but don't print it)
        if [ -n "${{ secrets.TESTENGINE_LICENSE_KEY }}" ]; then
          echo "✓ SLM access key is configured"
          ACCESS_KEY_LENGTH=$(echo "${{ secrets.TESTENGINE_LICENSE_KEY }}" | wc -c)
          echo "SLM access key length: $ACCESS_KEY_LENGTH characters"
        else
          echo "❌ SLM access key is not configured"
          echo "Please add TESTENGINE_LICENSE_KEY to repository secrets (this is your SLM access key)"
          exit 1
        fi
        
        docker run -d \
          --name testengine \
          -p 8080:8080 \
          -e TESTENGINE_PASSWORD=admin \
          -e JVM_OPT_XMS="-Xms1g" \
          -e JVM_OPT_XMX="-Xmx2g" \
          --add-host host.docker.internal:host-gateway \
          smartbear/readyapi-testengine:latest
        
        echo "Container started, waiting for TestEngine to be ready..."
        
        # Optimized health check - single success is sufficient for ephemeral CI environment
        timeout 120s bash -c '
          attempt=0
          max_attempts=24  # 2 minutes max (24 * 5 seconds)
          
          while [ $attempt -lt $max_attempts ]; do
            echo "Attempt $((attempt+1))/$max_attempts: Testing TestEngine readiness..."
            
            # Single health check is sufficient - if it responds, it is ready
            if curl -fsS http://localhost:8080/api/v1/version >/dev/null 2>&1; then
              echo "✅ TestEngine is ready and responding!"
              exit 0
            fi
            
            echo "Not ready yet, waiting 5 seconds..."
            sleep 5
            attempt=$((attempt+1))
          done
          
          echo "❌ TestEngine failed to start within 2 minutes"
          docker logs testengine | tail -50
          exit 1
        '
        
    - name: Activate TestEngine license
      run: node scripts/activate-license.js
      
    - name: Upload ReadyAPI project to TestEngine
      id: upload
      run: |
        PROJECT_FILE="${{ github.event.inputs.project_name || 'te-sample-readyapi-project.xml' }}"
        echo "Uploading project: $PROJECT_FILE"
        
        # Capture output and get the last line (execution ID)
        OUTPUT=$(node scripts/upload-project.js "$PROJECT_FILE")
        EXECUTION_ID=$(echo "$OUTPUT" | tail -n 1)
        
        echo "Captured execution ID: $EXECUTION_ID"
        echo "execution_id=$EXECUTION_ID" >> $GITHUB_OUTPUT
        echo "✓ Job submitted and started automatically (no separate start call needed)"
        
    - name: Poll for execution completion
      id: poll
      run: |
        EXECUTION_ID="${{ steps.upload.outputs.execution_id }}"
        echo "Polling execution: $EXECUTION_ID"
        node scripts/poll-execution.js "$EXECUTION_ID"
        
    - name: Download test results  
      run: |
        EXECUTION_ID="${{ steps.upload.outputs.execution_id }}"
        echo "Downloading results using proper Accept headers for: $EXECUTION_ID"
        node scripts/download-results-fixed.js "$EXECUTION_ID"
        
    - name: Prepare test results for artifacts
      run: |
        TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
        EXECUTION_ID="${{ steps.upload.outputs.execution_id }}"
        
        if [ -d "temp-results" ]; then
          echo "✓ Test results found in temp-results/"
          ls -la temp-results/
          echo "execution_timestamp=${TIMESTAMP}" >> $GITHUB_OUTPUT
          echo "✓ Results prepared for artifact upload"
        else
          echo "⚠️ No results directory found"
        fi
      id: prepare
        
    - name: Upload test results as artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: readyapi-test-results-${{ steps.prepare.outputs.execution_timestamp || github.run_number }}
        path: temp-results/
        retention-days: 30
        
    - name: Cleanup TestEngine Container
      if: always()
      run: |
        echo "Stopping and removing TestEngine container..."
        docker stop testengine || true
        docker rm testengine || true
        echo "TestEngine container cleaned up"